#!/usr/bin/php
<?php

// include the common PHP code file
require("a2.php");

// PROGRAM BODY BEGINS

$usage = "Usage: $argv[0] sourceActor destActor";
$db = dbConnect(DB_CONNECTION);

// Check arguments
// if (count($argv) != 3 ) exit("$usage\n");

// dd(mkSQL($q, $argv[1]));
// query the first result
// $title = $argv[1];

$src  = $argv[1];
$dest = $argv[2];
// initial the edges array
$edges  = array();

$q ="select distinct src_id, dest_id from actor_path ;";
$r = dbQuery($db, $q);
while ($t = dbNext($r)){
  // 2-d array with index is int 
  $edges[(int)$t[0]][(int)$t[1]] = true;
}


/**
 * Use BFS to search the path to dest spcified 
 */

$seen = array();
// path is array of array(path obj?)
$path = array();

// this will be delete, only for testing
$src = (int) $src;
$dest = (int) $dest;

array_push($path, array($src));

// the end depth is given by specification 
$end_depth = 6;

while(
  ($next = array_shift($path)) &&
  sizeof($next) < $end_depth
){
  foreach ($edges[array_last($next)] as $neighbour => $value) {
    // we only use the keys in the array 
    // the key is the neighbour for the last node in next 
    if (empty($seen[$neighbour])) {
      // not seen
      // push a new route to search 

      // copy the whole array by assign 
      $new_path = $next; 
      array_push($new_path, $neighbour);
      
      array_push($path, $new_path);
    } else {
      // seen, dump this node 
    }
    
    if($neighbour == $dest){
      // stop the path search earlier 
      $end_depth(sizeof($next) + 1);
    }

  }
  dd($path);    
}





?>
