#!/usr/bin/php
<?php

// include the common PHP code file
require("a2.php");

// PROGRAM BODY BEGINS

$usage = "Usage: $argv[0] sourceActor destActor";
$db = dbConnect(DB_CONNECTION);

// Check arguments
// if (count($argv) != 3 ) exit("$usage\n");

// dd(mkSQL($q, $argv[1]));
// query the first result
// $title = $argv[1];

$src  = $argv[1];
$dest = $argv[2];
// initial the edges array
$edges  = array();

$q ="select distinct src_id, dest_id from actor_path ;";
$r = dbQuery($db, $q);
while ($t = dbNext($r)){
  // 2-d array with index is int 
  $edges[(int)$t[0]][(int)$t[1]] = true;
}


/**
 * Use BFS to search the path to dest spcified 
 */

$seen = array();
// searching path is array of array(actor_id)
$searching = array();
// the end depth is given by specification 
$end_depth = 6;
// successful path to the dest 
$success_path = array();

// this will be delete, only for testing
$src = (int) $src;
$dest = (int) $dest;


// init the 
array_push($searching, array($src));



// depth 1 example 1598 - 2591
// depth 2 example 1598 - 3926
while(
  ($next = array_shift($searching)) &&
  sizeof($next) < $end_depth
){
  foreach ($edges[array_last($next)] as $neighbour => $value) {
    // we only use the keys in the array 
    // the key is the neighbour for the last node in next 
    if (
      empty($seen[$neighbour]) || 
      // two path can be also the shortest path to this neighbour 
      $seen[$neighbour] == sizeof($next) + 1
    ) {
      // not seen
      // push a new route to search 

      // copy the whole array by assign 
      $new_path = $next; 
      array_push($new_path, $neighbour);
      // new path to search 
      array_push($searching, $new_path);
      // add this node as seen 

      // this the degree 
      $seen[$neighbour] = sizeof($new_path); 

      if($neighbour == $dest){
        // stop the path search earlier 
        $end_depth=sizeof($new_path) ;
        // push this path to be success ful path to dest 
        array_push($success_path, $new_path);
      }
    }
  }
}

/**
 * Translate the actor path to movie name's path
 */
$movie_path = array();
get_movie_path([1598,1631]);
get_movie_path([1598,1631]);
dd(get_movie_path([1598,1631]));





?>
