#!/usr/bin/php
<?php

// include the common PHP code file
require("a2.php");

// PROGRAM BODY BEGINS

$usage = "Usage: $argv[0] MovieName ListLength";
$db = dbConnect(DB_CONNECTION);

// Check arguments
if (count($argv) != 3 ) exit("$usage\n");

/**
 * Fetch the genre list from database
 */
$q = "
select namelist(g.genre) 
from movie as m 
join genre as g 
  on g.movie_id = m.id  
where lower(m.title)=lower(%s);
";

// dd(mkSQL($q, $argv[1]));
// query the first result
$title = $argv[1];

/**
 * Fetch the plot keywords from database 
 */

$q = "";

$limit = $argv[2];

// dd($limit);
// dd($arr);

// Get the return results
$q .= "
with g_movie as (
  select m.id, m.title, count(g2.*) as g_count from movie as m 
  left join genre as g2 
  on 
    g2.movie_id = m.id  and 
    g2.genre in 
    (select g.genre from genre as g 
    join movie as m 
    on 
      lower(m.title)=lower('".$title."') and
        m.id = g.movie_id
    )
  group by m.id, m.title
)

, k_movie as 
(
  select m.id, m.title, count(k2.*) as k_count from movie as m 
  left join keyword as k2 
  on 
    k2.movie_id = m.id  and 
    k2.keyword in 
    (select k.keyword from keyword as k 
    join movie as m 
    on 
      lower(m.title)=lower('".$title."') and
        m.id = k.movie_id
    )
  group by m.id, m.title
)

select 
  m.title, m.year, g.g_count, k.k_count, r.imdb_score, r.num_voted_users
from movie  as m 
-- similarity
join k_movie as k 
on k.id = m.id
join g_movie as g 
on g.id = m.id 
-- imdb rank and vote 
join rating as r
on r.movie_id = m.id 
where lower(m.title)<>lower('".$title."') 
order by 
  g.g_count desc,
  k.k_count desc,
  r.imdb_score desc,
  r.num_voted_users desc
limit ".$limit."
;
";
// dd($q);


// dd( mkSQL($q, $arr));
$r = dbQuery($db, $q);

// Iterate through the results and print
$i = 1;
while ($t = dbNext($r)) {
  echo "$i. $t[0]";
  if (!empty($t[1])){
    echo " (".$t[1].")";
  }
  echo " [";
  noEmptyEcho($t[2],", ");
  noEmptyEcho($t[3],", ");
  noEmptyEcho($t[4],", ");
  noEmptyEcho($t[5]);
  echo "]\n";
  $i++;
}

?>
